@startuml
!include fo-only.puml

node webapp{
	[webapp.bo.portal]
}


node intf_bo{
	[intf.bo]
}
	
node impl{
	[impl.bo]
}

[webapp.bo.portal] -down-> [intf.bo]


[impl.bo] -down-> [impl.biz]
[impl.bo] .up.> [intf.bo] : implements

@enduml