@startuml
!include fo-and-bo.puml

 
node cross_layer_constants

node intf_pso{
	[intf.pso]
} 

node impl{
	[impl.pso]
}

[impl.pso] -down-> [impl.biz]
[impl.pso] .up.> [intf.pso] : implements




@enduml